language: php

php:
    - 7.3
    - 7.4

sudo: false

before_install:
  - composer self-update

install:
  - travis_retry composer update --no-interaction --prefer-source

script:
  - composer phpcs
  - composer coverage-clover


after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

matrix:
  fast_finish: true


notifications:
    on_success: never
    on_failure: always
